### ISSUE TITLE
after installtion stuck in migration

### ISSUE THREAD

**Issue by amet123** [AgileShift/cargo_management#5]
Hi @JeansReal 

after installation stuck in migration

Thanks

**Comment by JeansReal** [comment]
Hello, can you share more info to help you

**Comment by amet123** [comment]
Hi @JeansReal 
pls check error 

![error](https://github.com/AgileShift/cargo_management/assets/326649/e2144f1a-53b2-4b41-a7e8-6d2d922ffa5e)

**Comment by hidayatmanusiya** [comment]
Hi @JeansReal
 
 I also get same error

**Comment by amet123** [comment]
Hi @JeansReal 

any solution

**Comment by JeansReal** [comment]
Hello friends

Issue is already resolved on branch **develop** or **v15**!

**Easypost** package was updated on Version 8 and the Error handling was refactored!
We are currently supporting version [9.2.0](https://github.com/EasyPost/easypost-python/releases/tag/v9.2.0)

If problem persist, you can always downgrade to [easypost v7](https://github.com/EasyPost/easypost-python/releases/tag/v7.15.0)
